GOOGLE_ANALYTICS_ID:
borrow_direct:
  api_key: ''
symws:
  url:
  headers: {}
  login_params: {}
sw:
  url: https://searchworks.stanford.edu/view/
EMAIL_TO: yolo@example.com
HOSTNAME: foo.example.com
ACCESS_SERVICES_EMAIL: greencirc@stanford.edu
RECAPTCHA:
  SITE_KEY: 6Lc6BAAAAAAAAChqRbQZcn_yyyyyyyyyyyyyyyyy
  SECRET_KEY: 6Lc6BAAAAAAAAKN3DRm6VA_xxxxxxxxxxxxxxxxx

auth:
  default_privgroups: []
  borrow_direct_privgroups:
    - stanford:stanford
    - stanford:academic
  eresources_privgroups:
    - stanford:stanford
    - stanford:academic
    - stanford:administrative
    - organization:sumc
    - sulair:proxy-access
    - lane:proxy-access
