GOOGLE_ANALYTICS_ID:
symws:
  url:
  headers: {}
  login_params: {}
sw:
  url: https://searchworks.stanford.edu/view/
EMAIL_TO: yolo@example.com
HOSTNAME: foo.example.com
ACCESS_SERVICES_EMAIL: greencirc@stanford.edu

resource_icons:
  Object: cube
  Academic Journal: book-2
  Archive/Manuscript: document-box-1
  Archived website: network-web
  Article: text-wrapping-1
  Book: book-1
  Dataset: business-chart-1
  Database: window-search
  Equipment: plug-2
  Image: photos-1
  Journal/Periodical: book-2
  Map: map-location
  Music recording: gramophone
  Music score: file-music
  Newspaper: newspaper-2
  Software/Multimedia: mouse-2
  Sound recording: microphone-2
  Video: film-2
