GOOGLE_ANALYTICS_ID:
borrow_direct:
  api_key: ''
symws:
  url:
  headers: {}
  login_params: {}
sw:
  url: https://searchworks.stanford.edu/view/
EMAIL_TO: yolo@example.com
HOSTNAME: foo.example.com
ACCESS_SERVICES_EMAIL: greencirc@stanford.edu
RECAPTCHA:
  SITE_KEY: 6Lc6BAAAAAAAAChqRbQZcn_yyyyyyyyyyyyyyyyy
  SECRET_KEY: 6Lc6BAAAAAAAAKN3DRm6VA_xxxxxxxxxxxxxxxxx

home_page_flash_message_html: |-
  <h1 class="h3 alert-heading">Welcome to the new My Library Account!</h1>

  <p>My Account has been completely re-designed. It shows more information, highlights items that need attention, requires fewer steps, and is easier to use on mobile devices.</p>

  <p class="mb-0">Use the feedback link to let us know what you think!</p>

symphony:
  host:

# A sufficiently large time used to sort nil values last
END_OF_DAYS: <%= Time.parse('2099-01-01') %>

PAYMENT_TYPES:
  AUTOREFUND: 'Returned'
  CANCEL: 'Removed'
  CARDSWIPE: 'Paid by credit card'
  CASH: 'Paid by cash'
  CHECK: 'Paid by check'
  CLMS-RTND: 'Processing claim'
  CREDITACCT: 'Returned'
  CREDITCARD: 'Paid by credit card'
  FORGIVEN: 'Forgiven'
  LIB-ERROR: 'Removed'
  NONE: 'Returned'
  REFUND: 'Removed'
  RETURNED: 'Returned'
  TRANS-BILL: 'Forgiven'
  U-REPLACED: 'Replacement provided'
  XREMBILL: 'Removed'

CHARGE_LIMIT_THRESHOLD: 25000

PATRON_STANDING:
  BARRED: 'Contact us'
  COLLECTION: 'Blocked'
  BLOCKED: 'Blocked'
  DELINQUENT: 'OK'
  OK: 'OK'

PATRON_PROFILE:
  MXFEE: 'Fee borrower'
  MXFEE-BUS: 'Fee borrower'
  MXFEE-LAW: 'Fee borrower'
  MXFEE-NO25: 'Fee borrower'
