GOOGLE_ANALYTICS_ID:
borrow_direct:
  api_key: ''
symws:
  url:
  headers: {}
  login_params: {}
sw:
  url: https://searchworks.stanford.edu/view/
EMAIL_TO: yolo@example.com
HOSTNAME: foo.example.com
ACCESS_SERVICES_EMAIL: greencirc@stanford.edu
RECAPTCHA:
  SITE_KEY: 6Lc6BAAAAAAAAChqRbQZcn_yyyyyyyyyyyyyyyyy
  SECRET_KEY: 6Lc6BAAAAAAAAKN3DRm6VA_xxxxxxxxxxxxxxxxx

home_page_flash_message_html: |-
  <h1 class="h3 alert-heading">Welcome to the new My Library Account!</h1>

  <p>My Account has been completely re-designed. It shows more information, highlights items that need attention, requires fewer steps, and is easier to use on mobile devices.</p>

  <p class="mb-0">Use the feedback link to let us know what you think!</p>

symphony:
  host:

# A sufficiently large time used to sort nil values last
END_OF_DAYS: <%= Time.parse('2099-01-01') %>

PAYMENT_TYPES:
  AUTOREFUND: 'Returned'
  CANCEL: 'Removed'
  CARDSWIPE: 'Paid by credit card'
  CASH: 'Paid by cash'
  CHECK: 'Paid by check'
  CLMS-RTND: 'Processing claim'
  CREDITACCT: 'Returned'
  CREDITCARD: 'Paid by credit card'
  FORGIVEN: 'Forgiven'
  LIB-ERROR: 'Removed'
  NONE: 'Returned'
  REFUND: 'Removed'
  RETURNED: 'Returned'
  TRANS-BILL: 'Forgiven'
  U-REPLACED: 'Replacement provided'
  XREMBILL: 'Removed'

CHARGE_LIMIT_THRESHOLD: 25000

PATRON_STANDING:
  BARRED: 'Contact us'
  COLLECTION: 'Blocked'
  BLOCKED: 'Blocked'
  DELINQUENT: 'OK'
  OK: 'OK'

PATRON_PROFILE:
  MXFEE: 'Fee borrower'
  MXFEE-BUS: 'Fee borrower'
  MXFEE-LAW: 'Fee borrower'
  MXFEE-NO25: 'Fee borrower'

FINE_STATUS:
  OVERDUE: 'Overdue item'
  RECALLOVD: 'Overdue recall'
  RESERVEOVD: 'Overdue course reserve'
  LOST: 'Lost item'
  REPLCMENT: 'Lost item'
  LOST-ILL: 'Lost interlibrary loan item'
  CLAIM-LOST: 'Lost item'
  CLAIM-FEE: 'Processing fee'
  PROCESSFEE: 'Processing fee'
  PROCESSING: 'Processing fee'
  DAMAGED: 'Damaged item'
  PRIVILEGES: 'Privileges fee'
  LOSTCARD: 'Lost card fee'
  LOSTKEY: 'Lost key fee'
  BILLED-OD: 'Lost item'
  BILLING-FEE: 'Processing fee'
  PRE-NOTIS: 'Lost item'
  PRE-UNICRN: 'Lost item'
  RECAL-BILL: 'Lost item'
  RECAL-FEE: 'Overdue recall'
  RECOD-MBIL: 'Lost item'
  RECOD-MFEE: 'Processing fee'
  RECOD-MOD: 'Lost item'
  BADCHECK: 'Privileges fee'
  LOSTRECALL: 'Lost item'
  MISC: 'Overdue item'

BORROW_DIRECT_CODE: BORROW_DIRECT
SHORT_TERM_LOAN_PERIODS:
  - HOURLY

# Request becomes ON_LOAN once we receive it (and should show as a request ready for pickup/checkout)
# Request becomes COMPLETED once the uesr returns it
BORROW_DIRECT_ACTIVE_REQUEST_STATUSES:
  - ENTERED
  - IN_PROCESS
  - SHIPPED

library_contact:
  ARS: 'soundarchive@stanford.edu'
  ART: 'artlibrary@stanford.edu'
  BIOLOGY: 'greencirc@stanford.edu'
  BUSINESS: 'library@gsb.stanford.edu'
  CHEMCHMENG: 'greencirc@stanford.edu'
  CLASSICS: 'classics@stanford.edu'
  EARTH-SCI: 'brannerlibrary@stanford.edu'
  EAST-ASIA: 'eastasialibrary@stanford.edu'
  EDUCATION: 'cubberley@stanford.edu'
  ENG: 'englibrary@stanford.edu'
  GREEN: 'greencirc@stanford.edu'
  HOOVER: 'hoover-library-archives@stanford.edu'
  HOPKINS: 'HMS-Library@lists.stanford.edu'
  HV-ARCHIVE: 'hoover-library-archives@stanford.edu'
  LANE-MED: 'laneaskus@stanford.edu'
  LATHROP: 'greencirc@stanford.edu'
  LAW: 'reference@law.stanford.edu'
  MATH-CS: 'greencirc@stanford.edu'
  MEDIA-MTXT: 'greencirc@stanford.edu'
  MUSIC: 'muslibcirc@stanford.edu'
  RUMSEYMAP: 'rumseymapcenter@stanford.edu'
  SAL: 'salcirculation@stanford.edu'
  SAL3: 'greencirc@stanford.edu'
  SAL-NEWARK: 'greencirc@stanford.edu'
  SCIENCE: 'sciencelibrary@stanford.edu'
  SPEC-COLL: 'specialcollections@stanford.edu'
  TANNER: 'tanner-library@stanford.edu'

library_map:
  ARS: 'Archive of Recorded Sound'
  ART: 'Art & Architecture Library (Bowes)'
  BIOLOGY: 'Biology Library (Falconer)'
  BORROW_DIRECT: 'BorrowDirect'
  BUSINESS: 'Business Library'
  CHEMCHMENG: 'Chemistry & ChemEng Library (Swain)'
  CLASSICS: 'Classics Library'
  EARTH-SCI: 'Earth Sciences Library (Branner)'
  EAST-ASIA: 'East Asia Library'
  EDUCATION: 'Education Library (Cubberley)'
  ENG: 'Engineering Library (Terman)'
  GREEN: 'Green Library'
  HOOVER: 'Hoover Library'
  HOPKINS: 'Marine Biology Library (Miller)'
  HV-ARCHIVE: 'Hoover Archives'
  LANE-MED: 'Medical Library (Lane)'
  LATHROP: 'Lathrop Library'
  LAW: 'Law Library (Crown)'
  MATH-CS: 'Math & Statistics Library'
  MEDIA-MTXT: 'Media & Microtext Center'
  MUSIC: 'Music Library'
  RUMSEYMAP: 'David Rumsey Map Center'
  SAL: 'SAL1&2 (on-campus shelving)'
  SAL3: 'SAL3 (off-campus storage)'
  SAL-NEWARK: 'SAL Newark (off-campus storage)'
  SCIENCE: 'Science Library (Li and Ma)'
  SPEC-COLL: 'Special Collections'
  TANNER: 'Philosophy Library (Tanner)'

pickup_libraries:
  - 'ART'
  - 'BUSINESS'
  - 'EARTH-SCI'
  - 'EAST-ASIA'
  - 'EDUCATION'
  - 'ENG'
  - 'GREEN'
  - 'HOPKINS'
  - 'LAW'
  - 'MUSIC'
  - 'SAL'
  - 'SCIENCE'

library_specific_pickup_libraries:
  ARS:
    - ARS
  HV-ARCHIVE:
    - HV-ARCHIVE
  LAW:
    - LAW
  RUMSEYMAP:
    - RUMSEYMAP
  SPEC-COLL:
    - SPEC-COLL

location_specific_pickup_libraries:
  PAGE-AR:
    - ART
    - SPEC-COLL
  PAGE-AS:
    - ARS
  PAGE-BI:
    - BIOLOGY
  PAGE-BU:
    - BUSINESS
  PAGE-CH:
    - CHEMCHMENG
  PAGE-EA:
    - EAST-ASIA
  HY-PAGE-EA:
    - EAST-ASIA
  L-PAGE-EA:
    - EAST-ASIA
  ND-PAGE-EA:
    - EAST-ASIA
  PAGE-ED:
    - EDUCATION
  PAGE-EN:
    - ENG
  PAGE-ES:
    - EARTH-SCI
  PAGE-GR:
    - GREEN
  PAGE-HA:
    - HV-ARCHIVE
  PAGE-HP:
    - GREEN
    - HOPKINS
  PAGE-IRON:
    - BUSINESS
  PAGE-LP:
    - MUSIC
    - MEDIA-MTXT
  PAGE-LW:
    - LAW
  PAGE-MA:
    - MATH-CS
  PAGE-MD:
    - MUSIC
    - MEDIA-MTXT
  PAGE-MP:
    - EARTH-SCI
  PAGE-MU:
    - MUSIC
  PAGE-RM:
    - RUMSEYMAP
  PAGE-SI:
    - SCIENCE
  PAGE-SP:
    - SPEC-COLL
