GOOGLE_ANALYTICS_ID:
symws:
  url:
  headers: {}
  login_params: {}
sw:
  url: https://searchworks.stanford.edu/view/
EMAIL_TO: yolo@example.com
HOSTNAME: foo.example.com
ACCESS_SERVICES_EMAIL: greencirc@stanford.edu

resource_icons:
  Object: cube
  Academic Journal: book-open-4
  Archive/Manuscript: box-1
  Archived website: network-web
  # Article: text-wrapping-1
  Book: book-open-4
  Dataset: graph-bar-2
  Database: window-search
  Equipment: plug-1
  Image: picture-2
  Journal/Periodical: book-open-4
  Map: map-pin-1
  Music recording: turntable
  Music score: file-music-1
  Newspaper: newspaper
  Software/Multimedia: mouse
  Sound recording: microphone-3
  Video: camera-film-1
